import React from "react";

const HeroSection = () => {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section with Grid Background */}
      <section className="relative min-h-screen bg-gray-50 overflow-hidden">
        {/* Grid Background */}
        <div
          className="absolute inset-0 opacity-30"
          style={{
            backgroundImage: `
              linear-gradient(to bottom, rgba(156, 163, 175, 0.5) 1px, rgba(229, 231, 235, 0.2) 1px),
              linear-gradient(to right, rgba(156, 163, 175, 0.5) 1px, rgba(229, 231, 235, 0.2) 1px)
            `,
            backgroundSize: "80px 80px",
          }}
        />

        {/* Hero Content */}
        <div className="relative z-10 flex items-center min-h-screen">
          <div className="max-w-7xl mx-auto px-8">
            <div className="max-w-3xl">
              <h1 className="text-6xl md:text-7xl font-bold text-gray-900 mb-8 leading-tight">
                Explore AI Generated Images
              </h1>
              <p className="text-xl text-gray-600 mb-12 leading-relaxed max-w-2xl">
                Discover stunning artwork created by artificial intelligence.
                Browse thousands of unique, high-quality images generated by
                cutting-edge AI technology.
              </p>
              <div className="flex items-center space-x-6">
                <button className="bg-blue-600 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:bg-blue-700 transition-colors">
                  Get started
                </button>
                <button className="flex items-center text-gray-700 font-semibold text-lg hover:text-gray-900 transition-colors">
                  Learn more
                  <svg
                    className="ml-2 w-5 h-5"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M17 8l4 4m0 0l-4 4m4-4H3"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HeroSection;
